intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import libs += libcrails%lib{crails}

lib{crails-templates}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-templates}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{crails-templates}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-templates}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-templates}: bin.lib.version = "-$version.project_id"
else
  lib{crails-templates}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/crails/
  install.subdirs = true
}
